name: Deploy docker image to GitHub Registry

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Devops Project
    runs-on: ubuntu-latest
    env:
      PM2_PUBLIC_KEY: ${{ secrets.PM2_PUBLIC_KEY }}
      PM2_PRIVATE_KEY: ${{ secrets.PM2_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dvops-project-dcf:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PM2_PUBLIC_KEY=${{ secrets.PM2_PUBLIC_KEY }}
            PM2_PRIVATE_KEY=${{ secrets.PM2_PRIVATE_KEY }}
      - name: Verify PM2 Connection
        run: |
          docker run -d --name pm2-app \
            -e PM2_PUBLIC_KEY=${{ secrets.PM2_PUBLIC_KEY }} \
            -e PM2_PRIVATE_KEY=${{ secrets.PM2_PRIVATE_KEY }} \
            -e PM2_MACHINE_NAME=github-actions-${{ github.run_id }} \
            ${{ vars.DOCKERHUB_USERNAME }}/dvops-project-dcf:latest
          
          # Wait for container to start and PM2 to initialize
          sleep 15
          
          # Check if PM2 is running and connected
          docker exec pm2-app pm2 list || true
          docker exec pm2-app pm2 plus info || true
          
          # Check container logs for connection status
          docker logs pm2-app
          
          # Verify PM2 connection explicitly
          docker exec pm2-app sh -c 'pm2 link 8nnq1gobty5fv33 li58btqtkcia788'