name: Deploy docker image to GitHub Registry

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Devops Project
    runs-on: ubuntu-latest
    env:
      PM2_PUBLIC_KEY: ${{ secrets.PM2_PUBLIC_KEY }}
      PM2_PRIVATE_KEY: ${{ secrets.PM2_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dvops-project-dcf:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PM2_PUBLIC_KEY=${{ secrets.PM2_PUBLIC_KEY }}
            PM2_PRIVATE_KEY=${{ secrets.PM2_PRIVATE_KEY }}
      - name: Verify PM2 Connection
        run: |
          docker run -d --name pm2-app \
            ${{ vars.DOCKERHUB_USERNAME }}/dvops-project-dcf:latest
          
          sleep 10
          docker logs pm2-app

      - name: Handle deployment failure
        if: failure()
        run: |
          docker logs pm2-app || true
          docker rm -f pm2-app || true