name: Test Frontend and Backend

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      DEBUG: true
      NODE_ENV: "development"
      POSTGRES_CONNECTION_URL: "postgresql://postgres:test123@localhost:5432/postgres"
      POSTGRES_PASSWORD: "QTadFsylIQlo"
      JWT_SECRET: "test456"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Start Docker Compose services
      - name: Start services with Docker Compose
        run: docker compose up -d --wait --wait-timeout 30

      # Push database schema with drizzle-kit
      - name: Setup database schema with drizzle-kit
        run: npx drizzle-kit push

      - name: Run backend tests with Jest
        run: npm run test:api

      - name: Run Puppeteer tests
        run: npm run test:ui

      # Stop Docker Compose services
      - name: Stop Docker Compose services
        run: docker compose down