name: Test Pipeline

on:
  push:
  pull_request:
    
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      POSTGRES_PASSWORD: "QTadFsylIQlo"
      JWT_SECRET: "yO6txk2UBKuclKQZ"
      PORT: 3000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Start Dev Server
        run: npm run dev & # Run in background
        
      - name: Start Database
        run: docker compose up db -d

      - name: Push Database Schema
        run: npx drizzle-kit push

      - name: Run Backend Tests
        run: npm run test:api

      - name: Run Frontend Tests
        run: npm run test:ui

      - name: Stop Docker Services
        if: always()
        run: docker compose down

      - name: Stop Dev Server
        if: always()
        run: |
          pkill -f "npm run dev"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: test-results/